### PR TITLE
feat: add field block_number to Notification entity

### PR DESCRIPTION
**Pull request by JackyRahman**
### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2656

### Changelog
- [feat: add blocknumber in notification entity](https://github.com/debionetwork/debio-background-worker/commit/2cca0e7d73c42f9a3a9b42ed6f541a383d063eab)
- [feat: insert blockNumber](https://github.com/debionetwork/debio-background-worker/commit/ec7d9c358a95b9b33572658b54f21101ce6a629f)

### E2E Test Result
- Indexer:
- Scheduler: 
image

- Listener:

### CODE REVIEW

**Review by agustinustheo — CHANGES_REQUESTED** [review]
Waiting until integration tests are run by @rubenkristian

**Review by rubenkristian — CHANGES_REQUESTED** [review]
get error when insert notification.
please add block_number when insert notification in insert method from NotificationService class.

**Comment by rubenkristian** [comment]
Listener:
image
Indexer:
image
Scheduler:
image

**Review by rubenkristian — APPROVED** [review]
LGTM

**Review by agustinustheo — APPROVED** [review]

**Pull request merged**
