### PR TITLE
[DBIO-1715 & DBIO-1730] Create & Update index genetic analysis order + Unit Testing

### PR DESCRIPTION
**Pull request by rubenkristian**
### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-1715
- https://blocksphere2020.atlassian.net/browse/DBIO-1730

### Changelog/Description 🗒️
- create genetic analysis order event handler
- create index genetic analysis order in elasticsearch
- unit testing for genetic analysis order

### WARNING ⚠️
-

### CODE REVIEW

**Review by agustinustheo — CHANGES_REQUESTED** [review]
Have you tested it on a running Blockchain node yet? Please test it first because AFAIK, the node is going to be deployed in the dev environment soon.

**Review by agustinustheo — APPROVED** [review]

**Review by agustinustheo — DISMISSED** [review]
Please fix the tests first.

**Comment by agustinustheo** [comment]
Tests are still failing? @rubenkristian

**Comment by agustinustheo** [comment]
Tests are still failing? @rubenkristian

**Review by hilyds — APPROVED** [review]

**Pull request merged**
